### ISSUE TITLE
[FEAT. REQUEST] built-in speech synthesizer

### ISSUE THREAD

**Issue by michail-vestnik** [nao1215/speaker#3]
Hi! 

Is it possible to use the built-in speech synthesizer?
Is it possible to optionally use google-translate synthesizer (default) and others to choose from?

ありがとうございました

**Comment by nao1215** [comment]
Hi, @MichailVestnik 

> Is it possible to use the built-in speech synthesizer?

It's difficult because I don't have the motivation to do it.
I can do what I want to do in the current state.
So I have no intention of adding a built-in speech synthesizer.

> Is it possible to optionally use google-translate synthesizer (default) and others to choose from?

For example, if you want to use google-translate synthesizer, you need an access token.
Also, if you translate a certain amount of words, you will have to pay for it.
I find token setting cumbersome. Also, I don't want to include in the code what payments will occur.

Спасибо.
